---
- name: Get Content Host info from Old Satellite
  uri:
    url: "{{ satellite_migration_old_satellite }}/api/v2/hosts/{{ ansible_fqdn }}"
    user: "{{ satellite_migration_old_username }}"
    password: "{{ satellite_migration_old_password }}"
    force_basic_auth: "{{ satellite_migration_force_basic_auth }}"
    validate_certs: "{{ satellite_migration_validate_certs }}"
    method: "GET"
    status_code: 200
  register: satellite_migration_content_host_info.json
