---

- become: true
  block:

  - name: Unregister hosts From Satellite
    community.general.redhat_subscription:
      state: "absent"

  - name: Clean subscription-manager
    shell: /usr/bin/subscription-manager clean

  - name: Uninstall old the Katello RPM
    yum:
      name: "katello-ca-consumer*"
      state: absent
