---
- name: Check variables
  assert:
    that:
      - satellite_migration_url is defined
      - satellite_migration_username is defined
      - satellite_migration_password is defined
      - satellite_migration_force_basic_auth is defined
      - satellite_migration_validate_certs is defined
      - (satellite_migration_organization_id is defined or satellite_migration_organization is defined)
      - satellite_migration_location_id is defined or satellite_migration_location is defined
      - satellite_migration_hostgroup_id is defined or satellite_migration_hostgroup is defined
      - satellite_migration_setup_insights is defined
      - satellite_migration_setup_remote_execution is defined
      - satellite_migration_insecure is defined
      - satellite_migration_token_life_time is defined
      - satellite_migration_update_packages is defined
      - satellite_migration_force is defined
      - satellite_migration_ignore_subman_errors is defined
    fail_msg: "Mandatory variables not defined"

- name: Get Organization ID
  include_tasks: get_organization_id.yaml
  when: satellite_migration_organization_id is not defined and satellite_migration_organization is defined

- name: Get Location ID
  include_tasks: get_location_id.yaml
  when: satellite_migration_location_id is not defined and satellite_migration_location is defined

- name: Get Hostgroup ID
  include_tasks: get_hostgroup_id.yaml
  when: satellite_migration_hostgroup_id is not defined and satellite_migration_hostgroup is defined

- name: Get operatingsystem ID
  include_tasks: get_operatingsystem_id.yaml
  when: satellite_migration_operatingsystem_id is not defined and satellite_migration_operatingsystem is defined

- name: Get Lifecycle Environment ID
  include_tasks: get_lifecycle_environment_id.yaml
  when: satellite_migration_lifecycle_environment_id is not defined and satellite_migration_lifecycle_environment is defined

- name: Get registration command from Satellite
  uri:
    url: "{{ satellite_migration_url }}/api/registration_commands"
    user: "{{ satellite_migration_username }}"
    password: "{{ satellite_migration_password }}"
    force_basic_auth: "{{ satellite_migration_force_basic_auth }}"
    validate_certs: "{{ satellite_migration_validate_certs }}"
    method: "POST"
    body_format: "json"
    body:
      registration_command:
        organization_id: "{{ satellite_migration_organization_id }}"
        location_id: "{{ satellite_migration_location_id }}"
        hostgroup_id: "{{ satellite_migration_hostgroup_id }}"
        operatingsystem_id: "{{ satellite_migration_operatingsystem_id | default(omit) }}"
        smart_proxy_id: "{{ satellite_migration_smart_proxy_id | default(omit) }}"
        setup_insights: "{{ satellite_migration_setup_insights }}"
        setup_remote_execution: "{{ satellite_migration_setup_remote_execution }}"
        insecure: "{{ satellite_migration_insecure }}"
        jwt_expiration: "{{ satellite_migration_token_life_time }}"
        packages: "{{ satellite_migration_packages | default(omit) }}"
        update_packages: "{{ satellite_migration_update_packages }}"
        repo: "{{ satellite_migration_repo | default(omit) }}"
        repo_gpg_key_url: "{{ satellite_migration_repo_gpg_key_url | default(omit) }}"
        activation_keys: "{{ satellite_migration_activation_keys | default(omit) }}"
        lifecycle_environment_id: "{{ satellite_migration_lifecycle_environment_id | default(omit) }}"
        force: "{{ satellite_migration_force }}"
        ignore_subman_errors: "{{ satellite_migration_ignore_subman_errors }}"
    status_code: 200
  register: satellite_migration_result


# Register command var in localhost hostvar
- block:

  - name: Set registration command
    set_fact:
      satellite_registration_command: "{{ satellite_migration_result.json.registration_command }}"

  - name: Registration Command
    debug:
      msg: "{{ hostvars['localhost'].satellite_registration_command }}"

  delegate_to: localhost
  delegate_facts: true
