---
- name: Get registration command from Satellite
  uri:
    url: "{{ satellite_migration_url }}/api/registration_commands"
    user: "{{ satellite_migration_username }}"
    password: "{{ satellite_migration_password }}"
    force_basic_auth: "{{ satellite_migration_force_basic_auth }}"
    validate_certs: "{{ satellite_migration_validate_certs }}"
    method: "POST"
    body_format: "json"
    body:
      registration_command:
        organization_id: "{{ satellite_migration_organization_id }}"
        location_id: "{{ satellite_migration_location_id }}"
        hostgroup_id: "{{ satellite_migration_hostgroup_id | default(omit) }}"
        operatingsystem_id: "{{ satellite_migration_operatingsystem_id | default(omit) }}"
        smart_proxy_id: "{{ satellite_migration_smart_proxy_id | default(omit) }}"
        setup_insights: "{{ satellite_migration_setup_insights }}"
        setup_remote_execution: "{{ satellite_migration_setup_remote_execution }}"
        insecure: "{{ satellite_migration_insecure }}"
        jwt_expiration: "{{ satellite_migration_token_life_time }}"
        packages: "{{ satellite_migration_packages | default(omit) }}"
        update_packages: "{{ satellite_migration_update_packages }}"
        repo: "{{ satellite_migration_repo | default(omit) }}"
        repo_gpg_key_url: "{{ satellite_migration_repo_gpg_key_url | default(omit) }}"
        activation_keys:
          - "{{ satellite_migration_ak | default(omit) }}"
        lifecycle_environment_id: "{{ satellite_migration_lifecycle_environment_id | default(omit) }}"
        force: "{{ satellite_migration_force }}"
        ignore_subman_errors: "{{ satellite_migration_ignore_subman_errors }}"
    status_code: 200
  register: satellite_migration_result

- name: Set registration command
  set_fact:
    satellite_registration_command: "{{ satellite_migration_result.json.registration_command }}"

- name: Registration Command
  debug:
    var: satellite_registration_command 
