---

- name: Get repository list
  shell: "subscription-manager repos --list-enabled | grep -P '^Repo ID:' |  awk -F : '{print $2 }' | sed 's/ //g'"
  become: true
  register: repositories

- debug:
    var: repositories

- name: Backup repositories to tmp
  lineinfile:
    path: "{{ satellite_migration_local_tmp_path }}/repositories.tmp"
    create: true
    state: present
    line: "{{ item }}"
  loop: "{{ repositories.stdout_lines }}"
