- name: Get Content Host info from old Satellite
  include_tasks: content/get_content_host_info.yaml

- name: Get Content IDs from new Satellite
  include_tasks: content/get_content_ids.yaml

- name: Get Repositories from the Host
  include_tasks: repositories/get_repositories.yaml
  when: satellite_migration_keep_repositories

- name: Host migration
  when: not satellite_migration_dry_run
  block:

    - name: Deregister hosts from old Satellite
      include_tasks: 
        file: register/deregister.yaml

    - name: Register hosts in new Satellite
      include_tasks: 
        file: register/register.yaml

    - name: Enable Repositories
      include_tasks: 
        file: repositories/set_repositories.yaml
      when: satellite_migration_keep_repositories
