- name: Get Repositories
  include_tasks: repositories/get_repositories.yaml
  when: satellite_migration_keep_repositories

- name: Deregister hosts from old Satellite
  include_tasks: register/deregister.yaml

- name: Register hosts in new Satellite
  include_tasks: register/register.yaml

- name: Enable Repositories
  include_tasks: repositories/set_repositories.yaml
  when: satellite_migration_keep_repositories
