- name: Get Registration Command
  include_tasks: get_registration_command.yaml

- name: Execute Satellite registration command
  shell: "export LANG=en && {{ hostvars['localhost']['satellite_registration_command'] }}"
  become: true
  register: satellite_registration_execution_result

- name: Show output
  debug:
    var: satellite_registration_execution_result

