- name: Get Registration Command
  include_tasks: register/get_registration_command.yaml
  run_once: true

- name: Fail if registration command is undefined
  fail:
    msg: 'Registration command is undefined'
  when: hostvars['localhost']['satellite_registration_command'] is not defined

- name: Execute Satellite registration command
  shell: "export LANG=en && unset http_proxy && unset HTTP_PROXY && unset https_proxy && unset HTTPS_PROXY && {{ hostvars['localhost']['satellite_registration_command'] }}"
  become: true
  register: satellite_registration_execution_result

- name: Show output
  debug:
    var: satellite_registration_execution_result

